name: Auto Deploy to Netlify

on: 
  push: 
    branches: ["main"] 
  workflow_dispatch: 

jobs: 
  auto-deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the repository
        uses: actions/checkout@v3 

   
      - name: Publish to Netlify
        uses: netlify/actions/cli@master 
        with: 
          args: deploy --dir=build --prod 
        env: 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
